steps:
  # ビルド
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--no-cache",
        "--build-arg",
        "NEXT_ORIGIN=${_NEXT_ORIGIN}",
        "--build-arg",
        "NEXT_RESAS_API_KEY=${_NEXT_RESAS_API_KEY}",
        "--build-arg",
        "BASIC_AUTH_USER=${_BASIC_AUTH_USER}",
        "--build-arg",
        "BASIC_AUTH_PASSWORD=${_BASIC_AUTH_PASSWORD}",
        "-t",
        "${_REGISTRY}",
        ".",
      ]
    id: Build

  # プッシュ
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_REGISTRY}"]
    id: Push

  # デプロイ
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "${_DEPLOY}",
        "--image",
        "${_REGISTRY}",
        "--region",
        "asia-northeast1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
    id: Deploy

images:
  - ${_REGISTRY}

substitutions:
  _IMAGE_NAME: "docker_image"
  _DEPLOY: "deploy"
  _REGISTRY: "asia.gcr.io/${PROJECT_ID}/${_IMAGE_NAME}"

options:
  dynamic_substitutions: true # これを追加すると、substitutionsが動的になる
  substitution_option: "ALLOW_LOOSE"
